name: 'Evaluate agents via battle, example for trained chess agent vs random'
cmd: battle
env:
  name: mychess6x6
  n_max_episode_steps: 200
evaluate:
  evaluate_n_games: 100
  randomize_n_turns: 0    # Number of first turns to play randomly (helps to evaluate deterministic players)
infra:
  threads_cnt: 5
  device: cpu
player1:
  kind: q_player
  model:
    value:
      class: ValueModel66_v11
    self_learner:
      class: SelfLearningModel66_v11
    checkpoint: 'environments/mychess6x6_v11_checkpoint_20240822-132834.ckpt'
player2:
  kind: random
  # kind: two_step_lookahead
