name: 'Battle model vs random'
player1:
  kind: "random"
  # kind: "nn_player"
  # model:
  #   v:
  #     type: resnet
  #     res_blocks: 10
  #     filters: 80
  #   q:
  #     type: resnet
  #     res_blocks: 10
  #     filters: 80
player2:
  kind: "random"
env:
  n_max_episode_steps: 100
infra:
  n_threads: 8
  evaluate_n_games: 100