name: 'Battle model vs random'
player1:
  # kind: "random"
  # kind: "one_step_lookahead"
  # kind: "two_step_lookahead"
  # kind: "v_resnet_player"
  kind: "q_resnet_player"
  model:
    v:
      type: resnet
      res_blocks: 11
      filters: 96
    q:
      type: resnet
      res_blocks: 11
      filters: 96
    checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241228-123713*'

player2:
  # kind: "random"
  # kind: "one_step_lookahead"
  # kind: "two_step_lookahead"
  kind: "q_resnet_player"
  model:
    v:
      type: resnet
      res_blocks: 11
      filters: 96
    q:
      type: resnet
      res_blocks: 11
      filters: 96
    # checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241219-103526*'
    # checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241222-173728*'
    # checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241224-104436*'
    # checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241225-104038*'
    # checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241228-123713*'
    # checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241229-131916*'

  # kind: "q_resnet_player"
  # model:
  # v:
  #    type: resnet
  #    res_blocks: 16
  #    filters: 128
  #  q:
  #    type: resnet
  #    res_blocks: 16
  #    filters: 128
  #  checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/picked_checkpoints/vast/ckpt_20241214-090055*'

battle:
  random_first_turns: 2
env:
  n_max_episode_steps: 500
infra:
  gpu: 0                               # gpu id, use -1 for cpu
  evaluate_n_games: 1000
