name: 'Battle model vs random'
player1:
  # kind: "random"
  # kind: "one_step_lookahead"
  # kind: "two_step_lookahead"
  kind: "vq_resnet_player"
  model:
    v:
      type: resnet
      res_blocks: 3
      filters: 80
    q:
      type: resnet
      res_blocks: 3
      filters: 80

player2:
  kind: "random"
  # kind: "two_step_lookahead"
env:
  n_max_episode_steps: 500
infra:
  gpu: -1                               # gpu id, use -1 for cpu
  evaluate_n_games: 100