name: 'Battle model vs random'
player1:
  # kind: "random"
  # kind: "one_step_lookahead"
  # kind: "two_step_lookahead"
  # kind: "q_resnet_player"
  kind: "v_resnet_player"      # this player uses V model for actions
  model:
    v:
      type: resnet
      res_blocks: 3
      filters: 80
    q:
      type: resnet
      res_blocks: 3
      filters: 80
    checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241129-104608*'

player2:
  kind: "random"
  # kind: "two_step_lookahead"

env:
  n_max_episode_steps: 500
infra:
  gpu: -1                               # gpu id, use -1 for cpu
  evaluate_n_games: 30