name: 'Battle model vs random'
player1:
  # kind: "random"
  # kind: "one_step_lookahead"
  # kind: "two_step_lookahead"
  # kind: "v_resnet_player"
  kind: "q_resnet_player"
  model:
    v:
      type: resnet
      res_blocks: 3
      filters: 80
    q:
      type: resnet
      res_blocks: 3
      filters: 80
    checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241207-092128*'

player2:
  # kind: "random"
  # kind: "one_step_lookahead"
  # kind: "two_step_lookahead"
  kind: "q_resnet_player"
  model:
    v:
      type: resnet
      res_blocks: 3
      filters: 80
    q:
      type: resnet
      res_blocks: 3
      filters: 80
    checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241207-205615*'
battle:
  random_first_turns: 2
env:
  n_max_episode_steps: 500
infra:
  gpu: 0                               # gpu id, use -1 for cpu
  evaluate_n_games: 1000