name: 'Battle model vs random'
player1:
  kind: "vq_resnet_player"
  model:
    v:
      type: resnet
      res_blocks: 10
      filters: 80
    q:
      type: resnet
      res_blocks: 10
      filters: 80
player2:
  kind: "random"
env:
  n_max_episode_steps: 500
infra:
  n_threads: 8
  evaluate_n_games: 100