name: 'Example training run'
env:
  n_max_episode_steps: 500
model:
  v:
    type: resnet
    res_blocks: 11
    filters: 96
  q:
    type: resnet
    res_blocks: 11
    filters: 96
training:
  n_high_level_iterations: 1000
  q_train_sub_iterations: 1
  v_train_episodes: 5000
  q_train_episodes: 1000
  dataset_drop_ratio: 0.7
  tree_num_q_s_a_calls: 100
  tree_max_depth: 10000
  # exploration_full_random: 1      # pick random moves during V training (for debugging)
  exploration_num_first_moves: 30
  q_self_play_batch_size: 256
  batch_size: 256
  learning_rate: 0.0003
  weight_decay: 0.00001
  checkpoints_dir: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints'

  # resume from checkpoint:
  # checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/picked_checkpoints/ckpt_20241213-021452*'

  is_test: 0    # apply various checks on each iteration
infra:
  gpu: 0                               # gpu id, use -1 for cpu
  n_threads: 5
  evaluate_n_games: 500
  losses_log_dir: '/home/excellent/ds/probs/probs_chess_cpp/logs'
