name: 'UCI engine configuration'
model:
  v:
    type: resnet
    res_blocks: 11
    filters: 96
  q:
    type: resnet
    res_blocks: 11
    filters: 96
  checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20241224-104436*'
env:
  n_max_episode_steps: 500
infra:
  gpu: 0                               # gpu id, use -1 for cpu
  # n_threads: 5
