name: 'UCI engine configuration'
model:
  v:
    type: resnet
    res_blocks: 11
    filters: 96
  q:
    type: resnet
    res_blocks: 11
    filters: 96
  checkpoint: '/home/excellent/ds/probs/probs_chess_cpp/checkpoints/ckpt_20250106-100812*'
env:
  n_max_episode_steps: 500
infra:
  gpu: 0                               # gpu id, use -1 for cpu
  q_agent_batch_size: 64
  uci_mode: 1                          # indicate program to work as UCI engine
  search_mode: 2                       # 0 - random; 1 - single call to Q model; 2 - full search